"""estado de las quejas

Revision ID: 53f661c21212
Revises: e0287233a3ea
Create Date: 2026-09-03 00:03:39.299667
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53f661c21212'
down_revision: Union[str, None] = 'e0287233a3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')

    # ### end Alembic commands ###
