"""esquema inicial

Revision ID: 6ab5d4601b89
Revises: 
Create Date: 2026-09-02 23:19:51.088208
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ab5d4601b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_review_url', sa.String(length=512), nullable=False),
    sa.Column('dashboard_token', sa.String(length=64), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_dashboard_token'), ['dashboard_token'], unique=True)

    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placements_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_placements_token'), ['token'], unique=True)

    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_placement_id'), ['placement_id'], unique=False)

    op.create_table('taps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taps_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taps_is_bot'), ['is_bot'], unique=False)
        batch_op.create_index(batch_op.f('ix_taps_placement_id'), ['placement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taps_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taps_session_id'))
        batch_op.drop_index(batch_op.f('ix_taps_placement_id'))
        batch_op.drop_index(batch_op.f('ix_taps_is_bot'))
        batch_op.drop_index(batch_op.f('ix_taps_business_id'))

    op.drop_table('taps')
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_placement_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_business_id'))

    op.drop_table('feedbacks')
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placements_token'))
        batch_op.drop_index(batch_op.f('ix_placements_business_id'))

    op.drop_table('placements')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_dashboard_token'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
