"""programa de sellos

Revision ID: cbc7dd6ed983
Revises: 9636fbe3c713
Create Date: 2026-09-04 13:10:26.723687

Fidelización digital sin app: la tarjeta de sellos de papel, en el teléfono.

Cuatro tablas nuevas y ni una columna tocada de las que ya existían, así que un
cliente con historial no corre ningún riesgo al aplicarla. Un negocio sin
programa no tiene fila en `loyalty_programs` y no paga nada por esto.

Las tablas de sellos y premios son un registro contable, no analítica: un sello
se canjea por algo que le cuesta plata al comercio. Por eso los sellos solo se
agregan —el consumo se anota en el premio, en `stamps_consumed`— y por eso el
premio guarda su propio texto y su propio costo en sellos: si el dueño cambia
mañana las condiciones, quien ya ganó tiene que poder cobrar lo que le
prometieron.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbc7dd6ed983'
down_revision: Union[str, None] = '9636fbe3c713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_cards_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_cards_token'), ['token'], unique=True)

    op.create_table('loyalty_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('stamps_required', sa.Integer(), nullable=False),
    sa.Column('reward', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_programs_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_loyalty_programs_placement_id'), ['placement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_programs_token'), ['token'], unique=True)

    op.create_table('loyalty_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('stamps_consumed', sa.Integer(), nullable=False),
    sa.Column('reward_text', sa.String(length=200), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_rewards_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_rewards_card_id'), ['card_id'], unique=False)

    op.create_table('loyalty_stamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_stamps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_stamps_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_stamps_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_stamps_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_stamps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_stamps_created_at'))
        batch_op.drop_index(batch_op.f('ix_loyalty_stamps_card_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_stamps_business_id'))

    op.drop_table('loyalty_stamps')
    with op.batch_alter_table('loyalty_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_rewards_card_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_rewards_business_id'))

    op.drop_table('loyalty_rewards')
    with op.batch_alter_table('loyalty_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_programs_token'))
        batch_op.drop_index(batch_op.f('ix_loyalty_programs_placement_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_programs_business_id'))

    op.drop_table('loyalty_programs')
    with op.batch_alter_table('loyalty_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_cards_token'))
        batch_op.drop_index(batch_op.f('ix_loyalty_cards_business_id'))

    op.drop_table('loyalty_cards')
    # ### end Alembic commands ###
