"""credenciales del panel

Revision ID: e0287233a3ea
Revises: cdd115ca0d87
Create Date: 2026-09-02 23:36:44.964201
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0287233a3ea'
down_revision: Union[str, None] = 'cdd115ca0d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default obligatorio: sin él, agregar columnas NOT NULL a una tabla
    # que ya tiene negocios falla. Los clientes existentes quedan sin
    # credenciales y no podrán entrar hasta que se les asignen.
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("login_email", sa.String(length=255), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=255), nullable=False, server_default="")
        )
        batch_op.create_index(batch_op.f("ix_businesses_login_email"), ["login_email"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_login_email'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('login_email')

    # ### end Alembic commands ###
